package com.weiqilab.hackathon.hackathonkit.fragments;


import android.databinding.ObservableArrayList;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.weiqilab.hackathon.hackathonkit.R;
import com.weiqilab.hackathon.hackathonkit.adapters.FriendUserAdapter;
import com.weiqilab.hackathon.hackathonkit.entities.UserEntity;

import java.util.List;

import io.rapid.ListUpdate;
import io.rapid.Rapid;
import io.rapid.RapidCallback;
import io.rapid.RapidCollectionSubscription;
import io.rapid.RapidDocument;


/**
 * A simple {@link Fragment} subclass.
 * Use the {@link FragmentUpcoming#newInstance} factory method to
 * create an instance of this fragment.
 */
public class FragmentUpcoming extends Fragment {
    //The key used to store arraylist of movie objects to and from parcelable
    private static final String STATE_MOVIES = "state_movies";
    private RecyclerView mRecyclerMovies;
    //the TextView containing error messages generated by Volley
    private TextView mTextError;

    public FragmentUpcoming() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment FragmentUpcoming.
     */
    // TODO: Rename and change types and number of parameters
    public static FragmentUpcoming newInstance(String param1, String param2) {
        FragmentUpcoming fragment = new FragmentUpcoming();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    private void unSubscribeFromRapid() {
        if(mSubscription != null) {
            mSubscription.unsubscribe();
        }
    }
    @Override
    public void onStop() {
        super.onStop();
        unSubscribeFromRapid();
    }

    @Override
    public void onStart() {
        super.onStart();
        subscribeDataFromRapid();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View layout = inflater.inflate(R.layout.fragment_upcoming, container, false);
        mView = layout;
        setUpAdapter();
        return layout;
    }



    public View mView;
    public FriendUserAdapter mAdapter;
    public RecyclerView mRecyclerView;

    //Rapid.io Hackathon
    private ObservableArrayList<UserEntity> mItems = new ObservableArrayList<>();
    @Nullable
    private RapidCollectionSubscription mSubscription;

    public void subscribeDataFromRapid() {

        mSubscription = Rapid.getInstance().collection("motiv8-users-mockup", UserEntity.class)
                .subscribeWithListUpdates(new RapidCallback.CollectionUpdates<UserEntity>() {
                    @Override
                    public void onValueChanged(List<RapidDocument<UserEntity>> rapidDocuments, ListUpdate listUpdate) {
                        mItems.clear();
                        for(RapidDocument<UserEntity> rapidDocument : rapidDocuments) {
                            mItems.add(rapidDocument.getBody());
                        }
                        listUpdate.dispatchUpdateTo(mAdapter);
                        mAdapter.notifyDataSetChanged();
                    }
                });
    }

    public void setUpAdapter(){
        mAdapter = new FriendUserAdapter(mItems,mView.getContext());
        mRecyclerView = (android.support.v7.widget.RecyclerView)mView.findViewById(R.id.listMovieUpcoming);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(mView.getContext()));
        mRecyclerView.setAdapter(mAdapter);
    }





    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //save the movie list to a parcelable prior to rotation or configuration change
    }
}

