package com.weiqilab.hackathon.hackathonkit.fragments;


import android.content.Context;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.android.volley.AuthFailureError;
import com.android.volley.NetworkError;
import com.android.volley.NoConnectionError;
import com.android.volley.ParseError;
import com.android.volley.ServerError;
import com.android.volley.TimeoutError;
import com.android.volley.VolleyError;
import com.bumptech.glide.Glide;
import com.bumptech.glide.request.animation.GlideAnimation;
import com.bumptech.glide.request.target.SimpleTarget;
import com.weiqilab.hackathon.hackathonkit.R;
import com.weiqilab.hackathon.hackathonkit.activities.UserEntity;
import com.weiqilab.hackathon.hackathonkit.adapters.AdapterMovies;
import com.weiqilab.hackathon.hackathonkit.callbacks.UpcomingMoviesLoadedListener;
import com.weiqilab.hackathon.hackathonkit.database.DBMovies;
import com.weiqilab.hackathon.hackathonkit.extras.MovieSorter;
import com.weiqilab.hackathon.hackathonkit.extras.SortListener;
import com.weiqilab.hackathon.hackathonkit.logging.L;
import com.weiqilab.hackathon.hackathonkit.MyApplication;
import com.weiqilab.hackathon.hackathonkit.pojo.Movie;
import com.weiqilab.hackathon.hackathonkit.task.TaskLoadUpcomingMovies;

import java.util.ArrayList;

import de.hdodenhof.circleimageview.CircleImageView;


/**
 * A simple {@link Fragment} subclass.
 * Use the {@link FragmentUpcoming#newInstance} factory method to
 * create an instance of this fragment.
 */
public class FragmentUpcoming extends Fragment implements SortListener, UpcomingMoviesLoadedListener {
    //The key used to store arraylist of movie objects to and from parcelable
    private static final String STATE_MOVIES = "state_movies";
    //the arraylist containing our list of box office his
    private ArrayList<Movie> mListMovies = new ArrayList<>();
    //the adapter responsible for displaying our movies within a RecyclerView
    private AdapterMovies mAdapter;
    //the recyclerview containing showing all our movies
    private RecyclerView mRecyclerMovies;
    //the TextView containing error messages generated by Volley
    private TextView mTextError;
    //the sorter responsible for sorting our movie results based on choice made by the user in the FAB
    private MovieSorter mSorter = new MovieSorter();

    public FragmentUpcoming() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment FragmentUpcoming.
     */
    // TODO: Rename and change types and number of parameters
    public static FragmentUpcoming newInstance(String param1, String param2) {
        FragmentUpcoming fragment = new FragmentUpcoming();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    public void onSortByName() {
        mSorter.sortMoviesByName(mListMovies);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    public void onSortByDate() {
        mSorter.sortMoviesByDate(mListMovies);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    public void onSortByRating() {
        mSorter.sortMoviesByRating(mListMovies);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View layout = inflater.inflate(R.layout.fragment_upcoming, container, false);

        return layout;
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //save the movie list to a parcelable prior to rotation or configuration change
    }

    private void handleVolleyError(VolleyError error) {
        //if any error occurs in the network operations, show the TextView that contains the error message
        mTextError.setVisibility(View.VISIBLE);
        if (error instanceof TimeoutError || error instanceof NoConnectionError) {
            mTextError.setText(R.string.error_timeout);

        } else if (error instanceof AuthFailureError) {
            mTextError.setText(R.string.error_auth_failure);
            //TODO
        } else if (error instanceof ServerError) {
            mTextError.setText(R.string.error_auth_failure);
            //TODO
        } else if (error instanceof NetworkError) {
            mTextError.setText(R.string.error_network);
            //TODO
        } else if (error instanceof ParseError) {
            mTextError.setText(R.string.error_parser);
            //TODO
        }
    }

    @Override
    public void onUpcomingMoviesLoaded(ArrayList<Movie> listMovies) {
        //mAdapter.setMovies(listMovies);
    }
}
class CustomUserTwoAdapter extends RecyclerView.Adapter<CustomUserTwoAdapter.ViewHolder>{

    public ArrayList<UserEntity> mDataSet;
    public LayoutInflater mInflater;
    public Context mContext;

    public CustomUserTwoAdapter(ArrayList<UserEntity> dataSet, Context context){
        this.mDataSet = dataSet;
        mInflater = LayoutInflater.from(context);
        mContext = context;

    }

    @Override
    public CustomUserTwoAdapter.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        // TODO inflate layout here
        View v = mInflater.inflate(R.layout.custom_user_item, parent, false);
        CustomUserTwoAdapter.ViewHolder vH = new CustomUserTwoAdapter.ViewHolder(v);
        return vH;
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {

        // TODO assign layout values here
        UserEntity me = mDataSet.get(position);
        holder.mUserNameTextView.setText(me.mProfileEntity.mName);
        holder.mUsercityTextView.setText(me.mProfileEntity.mCity);
        holder.mUserinterestsTextView.setText(android.text.TextUtils.join(", ", me.mInterests));
        displayPhotoURL(holder.mCircleImageView, me.mProfileEntity.mPicture, mContext);
    }

    @Override
    public long getItemId(int position) {
        return super.getItemId(position);
    }

    // TODO display profile picture here.
    public static void displayPhotoURL(final CircleImageView messengerImageView, String photoUrl, Context context) {
        if (photoUrl == null) {
            messengerImageView
                    .setImageDrawable(ContextCompat
                            .getDrawable(context,
                                    R.drawable.ic_account_circle_black_36px));
        } else {
            SimpleTarget target = new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap bitmap, GlideAnimation glideAnimation) {
                    messengerImageView.setImageBitmap(bitmap);
                }
            };
            Glide.with(context)
                    .load(photoUrl)
                    .asBitmap()
                    .into(target);
        }
    }

    @Override
    public int getItemCount() {
        return mDataSet.size();
    }

    public static class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener{

        // TODO create fields here for layout.
        CircleImageView mCircleImageView;
        TextView mUserNameTextView;
        TextView mUsercityTextView;
        TextView mUserinterestsTextView;

        public ViewHolder(View v){
            super(v);
            mCircleImageView = (CircleImageView) v.findViewById(R.id.userthumbnail);
            mUserNameTextView = (TextView) v.findViewById(R.id.username);
            mUsercityTextView = (TextView) v.findViewById(R.id.usercity);
            mUserinterestsTextView = (TextView) v.findViewById(R.id.userinterests);
        }

        @Override
        public void onClick(View view) {

        }
    }
}

